### ISSUE TITLE
Formulas del circulo

### ISSUE THREAD

**Issue by GersonLazaro** [ProgramacionCompetitivaUFPS/notebook#33]
Añadir fórmulas de segmento triangular, sector circular, corona circular y similares.

**Comment by Meyito** [comment]
Faltan también las otras formulas de áreas y eso :3

**Comment by GersonLazaro** [comment]
Pues para el area de figuras no regulares en el plano cartesiano está en la parte de geometria el método area. ¿O a que areas te refieres?
