### ISSUE TITLE
Disjoint Set

### ISSUE THREAD

**Issue by GersonLazaro** [ProgramacionCompetitivaUFPS/notebook#47]
El disjoint set está en java pero no en C++.

Si mal no recuerdo, es porque en c++ lo tenias metido en kruskall.

Eso está bien? Debería agregarse disjoint en c++? Deberia quitarse en java y dejarlo dentro de kruskall? O se deberia simplemente dejar así?

**Comment by Meyito** [comment]
En java estaba independiente porque lo maneje como una clase. Aún así dejare la implementación de DS en c++ también.

**Comment by GersonLazaro** [comment]
@Meyito osea, tal como está está bien?

**Comment by Meyito** [comment]
Osea que agregare el Disjoint en cpp también 😋
